# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad0d9a07d48651508d14cc80e4b2e424e739afcc41b15e446e7c35e3a08ffba23f104bcf32943f5c400e6ef350b1518ade141fddf26691801a9038f3afae550

test:
  secret_key_base: 7d0e32d7c00950d5913f7145e0ff09d31b4fda13426852bd6f8f3f9e588e56baeacc5d7b87ce65c5c4bdc62eddab944384c3324f6f04a0653621853781c181e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
